name: SDB
description: SDB mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.7
  shared_preferences: ^2.2.1
  get_it: ^7.6.0
  flutter_screenutil: ^5.9.0
  auto_route: ^7.8.3
  flutter_svg: ^2.0.7
  easy_localization: ^3.0.2
  dio: ^4.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  connectivity_plus: ^4.0.2
  intl_phone_field: ^3.2.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_avif: ^1.4.0
  animated_size_and_fade: ^3.0.1
  riverpod_lint: ^2.0.4
  cached_network_image: ^3.2.3
  riverpod_infinite_scroll: ^1.0.9
  infinite_scroll_pagination: ^3.2.0
  pull_to_refresh: ^2.0.0
  proste_indexed_stack: ^0.2.4

dev_dependencies:
  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.1
  freezed: ^2.4.2





flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lang/
    - assets/images/
    - assets/icon/svg/
    - assets/icon/png/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/ads/
    - assets/images/logo/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
